CREATE TABLE `alumni` (
  `alumni_id` int(11) NOT NULL,
  `alumni_user_id` int(11) NOT NULL,
  `Fname` varchar(45) DEFAULT NULL,
  `Minit` varchar(45) DEFAULT NULL,
  `LName` varchar(45) DEFAULT NULL,
  `user_name` varchar(45) DEFAULT NULL,
  `country` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `district` varchar(45) DEFAULT NULL,
  `tel_no` bigint(20) DEFAULT NULL,
  `Bdate` varchar(45) DEFAULT NULL,
  `e_mail` varchar(45) DEFAULT NULL,
  `password` varchar(45) DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  `class_info` int(11) NOT NULL,
  `university` varchar(45) NOT NULL,
  `department` varchar(45) NOT NULL,
  `gpa` float NOT NULL,
  PRIMARY KEY (`alumni_id`),
  KEY `alumni_user_id` (`alumni_user_id`),
  CONSTRAINT `alumni_ibfk_1` FOREIGN KEY (`alumni_user_id`) REFERENCES `user` (`user_id`),
  CONSTRAINT `gpa` CHECK ((`gpa` between 0 and 4))
)