CREATE TABLE `company_employee` (
  `company_employee_id` int(11) NOT NULL,
  `company_employee_user_id` int(11) NOT NULL,
  `Fname` varchar(45) DEFAULT NULL,
  `Minit` varchar(45) DEFAULT NULL,
  `Lname` varchar(45) DEFAULT NULL,
  `user_name` varchar(45) DEFAULT NULL,
  `country` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `district` varchar(45) DEFAULT NULL,
  `tel_no` bigint(20) DEFAULT NULL,
  `Bdate` varchar(45) DEFAULT NULL,
  `e_mail` varchar(45) DEFAULT NULL,
  `password` varchar(45) DEFAULT NULL,
  `sex` varchar(45) DEFAULT NULL,
  `salary` varchar(45) DEFAULT NULL,
  `company_name` varchar(45) DEFAULT NULL,
  `company_tax_no` bigint(20) DEFAULT NULL,
  `company_fax_no` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`company_employee_id`),
  KEY `company_employee_user_id` (`company_employee_user_id`),
  CONSTRAINT `company_employee_ibfk_1` FOREIGN KEY (`company_employee_user_id`) REFERENCES `user` (`user_id`),
  CONSTRAINT `salary` CHECK ((`salary` between 1 and 60000))
)